version: "3"
services:
  python:
    image: registry.cn-beijing.aliyuncs.com/yexiao/python-selenium
    restart: always
    #ports:
    #  - 8081:8081
    container_name: server-python-172.4.0.60
    volumes:
     - .:/opt/python
    command: sh +x /opt/python/app.sh
    networks:
      default:
        ipv4_address: 172.4.0.60
networks:
  default:
    external:
      name: 2019_nCoV_network
